// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitLabExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "GitLabExtension.a9fdb72d-4078-4095-bb92-8beb6ded2489";
        public const string Name = "GitLab Merge Request review";
        public const string Description = @"GitLab Merge Request review";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Alexey Sosnin";
        public const string Tags = "";
    }
}
